FROM oven/bun:latest

WORKDIR /usr/src/presentify

COPY . .

RUN bun install
RUN apt-get update -y && apt-get install -y openssl
RUN bunx prisma generate --no-engine && bun run build

CMD ["bun", "run", "dev"]
